# Generated by Django 4.2.7 on 2024-11-11 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("btsapp", "0002_tasks_scripts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scripts",
            old_name="datetime",
            new_name="created_date",
        ),
        migrations.RenameField(
            model_name="scripts",
            old_name="userid",
            new_name="devid",
        ),
        migrations.AddField(
            model_name="tasks",
            name="received_date",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("repid", models.AutoField(primary_key=True, serialize=False)),
                ("priority_level", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=200)),
                ("created_date", models.CharField(max_length=50)),
                (
                    "taskid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="btsapp.tasks"
                    ),
                ),
            ],
        ),
    ]
