# Generated by Django 4.2.7 on 2024-11-11 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("btsapp", "0003_rename_datetime_scripts_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="script",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="btsapp.scripts",
            ),
            preserve_default=False,
        ),
    ]
