# Generated by Django 4.2.7 on 2025-01-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("btsapp", "0006_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="scripts",
            name="requirements",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
