# Generated by Django 4.2.7 on 2025-02-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("btsapp", "0007_scripts_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="scripts",
            name="status",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
