# Generated by Django 4.2.7 on 2025-02-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("btsapp", "0008_scripts_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="scripts",
            name="assigned_to",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
