# Generated by Django 3.2.25 on 2025-02-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btsapp', '0009_scripts_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='requirements',
            field=models.TextField(default='indentation'),
        ),
    ]
