# Generated by Django 4.2.7 on 2024-11-09 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("btsapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                ("taskid", models.AutoField(primary_key=True, serialize=False)),
                ("assign_to", models.CharField(max_length=50)),
                ("script_from", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Scripts",
            fields=[
                ("scriptid", models.AutoField(primary_key=True, serialize=False)),
                ("filename", models.CharField(max_length=200)),
                ("upfile", models.FileField(upload_to="uploaded_scripts/")),
                ("datetime", models.CharField(max_length=100)),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="btsapp.user"
                    ),
                ),
            ],
        ),
    ]
