# Generated by Django 4.2.7 on 2024-11-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("btsapp", "0004_tasks_script"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="created_by",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
