# Generated by Django 4.2.11 on 2024-12-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btsapp", "0005_report_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("notif_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_email", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
        ),
    ]
