# Generated by Django 3.2.25 on 2025-02-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btsapp', '0010_tasks_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='requirements',
            field=models.TextField(default='no requirements provided'),
        ),
    ]
