# Generated by Django 3.2.25 on 2025-03-16 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btsapp', '0011_alter_tasks_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('website_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirements', models.TextField()),
                ('status', models.CharField(max_length=30)),
                ('assigned_to', models.CharField(max_length=50)),
                ('devid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btsapp.user')),
            ],
        ),
    ]
