# Generated by Django 3.2.25 on 2025-03-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btsapp', '0012_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteTasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('assign_to', models.CharField(max_length=50)),
                ('website_from', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=30)),
                ('received_date', models.CharField(max_length=100)),
                ('requirements', models.TextField(default='no requirements provided')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btsapp.website')),
            ],
        ),
    ]
