# Generated by Django 3.2.25 on 2025-03-16 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btsapp', '0013_websitetasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteReport',
            fields=[
                ('rep_id', models.AutoField(primary_key=True, serialize=False)),
                ('priority_level', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=50)),
                ('created_date', models.CharField(max_length=50)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btsapp.websitetasks')),
            ],
        ),
    ]
